### ISSUE TITLE
Map Statistics error

### ISSUE THREAD

**Issue by cdxemu** [JasonLautzenheiser/trizbort#575]
I get the following error whenever I attempt to view Map Statistics for a specific map, as if that particular file's statistics are somehow corrupted:

`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List~1.get_Item(Int32 index)
   at Trizbort.Domain.Application.MapStatistics.<>c.<get_UnlabeledConnections>b__63_0(Connection p)
   at System.Linq.Enumerable.Count[TSource](IEnumerable~1 source, Func~2 predicate)
   at Trizbort.Domain.Application.MapStatistics.get_UnlabeledConnections()
   at Trizbort.UI.MapStatisticsView.mapStatisticsString()
   at Trizbort.UI.MapStatisticsView.MapStatisticsView_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

The error started to occur when the map was much smaller/simpler than it is now (maybe 1/8 the current size). It also still occurs even if I delete everything and then add a single empty room. I haven't seen it happen with my other map files.

The map was created in 1.7.2, but I get the same error after updating to 1.7.4.1.

[map.zip](https://github.com/JasonLautzenheiser/trizbort/files/12081805/map.zip)

**Comment by cdxemu** [comment]
I was able to fix the error for now by deleting the following two lines from the .trizbort map file:
`<line id="85" name="" description="" startText="up" endText="down" />`
`<line id="497" name="" description="" style="dashed" flow="oneWay" startText="down" endText="up" />`

Orphaned lines with no connections, it seems?

I found these by doing a text comparison between a new map with only one empty room and the existing map file with only one empty room.

**Comment by JasonLautzenheiser** [comment]
fixed in 1.8
